url: https://martaymarkos.com

# Site settings
title: Marta & Markos
email: horrorivasfamily@gmail.com
description: "Para que nada nos separe, que nada nos una"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty

include: ['_gl_pages', '_en_pages', '_es_pages']
